# Bibliotheken importieren

In [2]:
import pandas as pd
import numpy as np

# Die 3 Dateien lesen

In [3]:
df_lieferanten = pd.read_csv('lieferanten_bereinigt.csv')
df_rechnungen = pd.read_csv('rechnungen_bereinigt.csv')
df_anomalien = pd.read_csv('labels_anomalien_bereinigt.csv')

# erste zwei DataFrame Tabellen über die Spalte lieferanten_id joinen

In [ ]:

df_joined = pd.merge(df_lieferanten, 
                     df_rechnungen, 
                     left_on='lieferanten_id', 
                     right_on='lieferanten_id',
                     how='inner')

# prüfen ob die join funktioniert hat

In [5]:
df_joined.head()

,lieferanten_id,lieferanten_name,stadt,plz,offizielle_iban,median_betrag_eur,streuung,transaktions_id,rechnungsnummer,rechnungsdatum,faelligkeitsdatum,iban,betrag_eur,waehrung,kostenstelle,buchender_mitarbeiter,ist_duplikat_kopie,ist_iban_abweichung,ist_betrags_ausreisser
0,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000063,RE-2026-00077,2026-01-03,2026-02-02,DE61756828670787846415,566352.0,EUR,KS-015,Beier,0,0,0
1,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000064,RE-2026-00110,2026-01-03,2026-02-02,DE61756828670787846415,267001.0,EUR,KS-009,Gehringer,0,0,0
2,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000091,RE-2026-00089,2026-01-04,2026-01-25,DE61756828670787846415,126893.0,EUR,KS-008,Weinhage,0,0,0
3,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000123,RE-2026-00099,2026-01-05,2026-01-26,DE61756828670787846415,201852.0,EUR,KS-001,Lübs,0,0,0
4,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000161,RE-2026-00049,2026-01-06,2026-01-27,DE61756828670787846415,319134.0,EUR,KS-022,Hänel,0,0,0

# Das DF df_anomalien über transaktions_id joinen

In [ ]:

df_joined = pd.merge(df_joined, df_anomalien, 
                     left_on='transaktions_id', 
                     right_on='transaktions_id', 
                     how='inner')

# Die drei df prüfen

In [7]:
df_joined.head()

,lieferanten_id,lieferanten_name,stadt,plz,offizielle_iban,median_betrag_eur,streuung,transaktions_id,rechnungsnummer,rechnungsdatum,...,waehrung,kostenstelle,buchender_mitarbeiter,ist_duplikat_kopie_x,ist_iban_abweichung_x,ist_betrags_ausreisser_x,ist_duplikat_kopie_y,ist_iban_abweichung_y,ist_betrags_ausreisser_y,hat_anomalie
0,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000063,RE-2026-00077,2026-01-03,...,EUR,KS-015,Beier,0,0,0,0,0,0,0.0
1,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000064,RE-2026-00110,2026-01-03,...,EUR,KS-009,Gehringer,0,0,0,0,0,0,0.0
2,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000091,RE-2026-00089,2026-01-04,...,EUR,KS-008,Weinhage,0,0,0,0,0,0,0.0
3,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000123,RE-2026-00099,2026-01-05,...,EUR,KS-001,Lübs,0,0,0,0,0,0,0.0
4,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000161,RE-2026-00049,2026-01-06,...,EUR,KS-022,Hänel,0,0,0,0,0,0,0.0

# Datentyp checken

In [8]:
df_joined.dtypes

lieferanten_id                  str
lieferanten_name                str
stadt                           str
plz                           int64
offizielle_iban                 str
median_betrag_eur           float64
streuung                    float64
transaktions_id                 str
rechnungsnummer                 str
rechnungsdatum                  str
faelligkeitsdatum               str
iban                            str
betrag_eur                  float64
waehrung                        str
kostenstelle                    str
buchender_mitarbeiter           str
ist_duplikat_kopie_x          int64
ist_iban_abweichung_x         int64
ist_betrags_ausreisser_x      int64
ist_duplikat_kopie_y          int64
ist_iban_abweichung_y         int64
ist_betrags_ausreisser_y      int64
hat_anomalie                float64
dtype: object

# die Spalte plz als string umwandeln, da es sich um eine Postleitzahl handelt

In [ ]:

df_joined['plz'] = df_joined['plz'].astype(str)

# die spalte hat_anomalie als integer umwandeln, da es sich um eine binäre Variable handelt

# Datentyp des Join checken

In [ ]:

df_joined['hat_anomalie'] = df_joined['hat_anomalie'].astype('Int64')

In [11]:
df_joined.dtypes

lieferanten_id                  str
lieferanten_name                str
stadt                           str
plz                             str
offizielle_iban                 str
median_betrag_eur           float64
streuung                    float64
transaktions_id                 str
rechnungsnummer                 str
rechnungsdatum                  str
faelligkeitsdatum               str
iban                            str
betrag_eur                  float64
waehrung                        str
kostenstelle                    str
buchender_mitarbeiter           str
ist_duplikat_kopie_x          int64
ist_iban_abweichung_x         int64
ist_betrags_ausreisser_x      int64
ist_duplikat_kopie_y          int64
ist_iban_abweichung_y         int64
ist_betrags_ausreisser_y      int64
hat_anomalie                  Int64
dtype: object

# prüfe ob es negative werte bei der spalte hat_anomalie gibt

In [ ]:

negative_values = df_joined[df_joined['hat_anomalie'] < 0]
print(negative_values.shape[0])

0

# prüfeob es noch fehlende Werte gibt bei der spalte hat_anomalie

In [ ]:

missing_values = df_joined[df_joined['hat_anomalie'].isnull()]
print(missing_values.shape[0])

80

# fehlende Werte in der Spalte hat_anomalie mit nan auffüllen
# die spalte als integrer umwandeln
# Fehlende werte in der Spalte hat_anomalie löschen

In [ ]:

df_joined['hat_anomalie'] = df_joined['hat_anomalie'].replace(['', 'nan', 'NaN', 'None', -1, '-1'], np.nan).astype('Int64')

df_joined['hat_anomalie'] = df_joined['hat_anomalie'].astype('Int64')

df_joined = df_joined.dropna(subset=['hat_anomalie'])

# prüfen, ob es noch fehlende Werte gibt

In [ ]:

df_joined.isna().sum()

lieferanten_id              0
lieferanten_name            0
stadt                       0
plz                         0
offizielle_iban             0
median_betrag_eur           0
streuung                    0
transaktions_id             0
rechnungsnummer             0
rechnungsdatum              0
faelligkeitsdatum           0
iban                        0
betrag_eur                  0
waehrung                    0
kostenstelle                0
buchender_mitarbeiter       0
ist_duplikat_kopie_x        0
ist_iban_abweichung_x       0
ist_betrags_ausreisser_x    0
ist_duplikat_kopie_y        0
ist_iban_abweichung_y       0
ist_betrags_ausreisser_y    0
hat_anomalie                0
dtype: int64

# alle string spalten as kategorische Variablen umwandeln

In [ ]:

for col in df_joined.columns:
    if df_joined[col].dtype == 'str':
        df_joined[col] = df_joined[col].astype('category')

# Datentyp prüfen

In [17]:
df_joined.dtypes

lieferanten_id              category
lieferanten_name            category
stadt                       category
plz                         category
offizielle_iban             category
median_betrag_eur            float64
streuung                     float64
transaktions_id             category
rechnungsnummer             category
rechnungsdatum              category
faelligkeitsdatum           category
iban                        category
betrag_eur                   float64
waehrung                    category
kostenstelle                category
buchender_mitarbeiter       category
ist_duplikat_kopie_x           int64
ist_iban_abweichung_x          int64
ist_betrags_ausreisser_x       int64
ist_duplikat_kopie_y           int64
ist_iban_abweichung_y          int64
ist_betrags_ausreisser_y       int64
hat_anomalie                   Int64
dtype: object

# lösche eine der spalten mit gleichen Inhalten

In [ ]:

column_to_loeschen = ['ist_duplikat_kopie_x', 'ist_iban_abweichung_x', 'ist_betrags_ausreisser_x']
df_joined = df_joined.drop(columns=column_to_loeschen, errors='ignore')

In [19]:
df_joined

,lieferanten_id,lieferanten_name,stadt,plz,offizielle_iban,median_betrag_eur,streuung,transaktions_id,rechnungsnummer,rechnungsdatum,faelligkeitsdatum,iban,betrag_eur,waehrung,kostenstelle,buchender_mitarbeiter,ist_duplikat_kopie_y,ist_iban_abweichung_y,ist_betrags_ausreisser_y,hat_anomalie
0,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000063,RE-2026-00077,2026-01-03,2026-02-02,DE61756828670787846415,566352.0,EUR,KS-015,Beier,0,0,0,0
1,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000064,RE-2026-00110,2026-01-03,2026-02-02,DE61756828670787846415,267001.0,EUR,KS-009,Gehringer,0,0,0,0
2,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000091,RE-2026-00089,2026-01-04,2026-01-25,DE61756828670787846415,126893.0,EUR,KS-008,Weinhage,0,0,0,0
3,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000123,RE-2026-00099,2026-01-05,2026-01-26,DE61756828670787846415,201852.0,EUR,KS-001,Lübs,0,0,0,0
4,L001,Dowerg,Unbekannt,33218,DE61756828670787846415,2217.42,1.02,T000161,RE-2026-00049,2026-01-06,2026-01-27,DE61756828670787846415,319134.0,EUR,KS-022,Hänel,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10195,L080,Butte,Gerolzhofen,81206,DE97332951796406441392,2436.19,0.84,T009702,RE-2026-00061,2026-09-16,2026-10-16,DE97332951796406441392,205362.0,EUR,KS-008,Haase,0,0,0,0
10196,L080,Butte,Gerolzhofen,81206,DE97332951796406441392,2436.19,0.84,T009703,RE-2026-00070,2026-09-16,2026-10-07,DE97332951796406441392,363004.0,EUR,KS-003,Heser,0,0,0,0
10197,L080,Butte,Gerolzhofen,81206,DE97332951796406441392,2436.19,0.84,T009932,RE-2026-00087,2026-09-22,2026-10-22,DE97332951796406441392,246873.0,EUR,KS-019,Hesse,0,0,0,0
10198,L080,Butte,Gerolzhofen,81206,DE97332951796406441392,2436.19,0.84,T010052,RE-2026-00119,2026-09-25,2026-10-25,DE97332951796406441392,203686.0,EUR,KS-003,Hörle,0,0,0,0
10199,L080,Butte,Gerolzhofen,81206,DE97332951796406441392,2436.19,0.84,T010165,RE-2026-00055,2026-09-28,2026-10-19,DE97332951796406441392,135045.0,EUR,KS-018,Hentschel,0,0,0,0

# Datei als csv speichern

In [ ]:

df_joined.to_csv('joined_tabellen_bereinigt.csv', index=False)